### ISSUE TITLE
`GraphView` button layout and window size

### ISSUE THREAD

**Issue by reelmatt** [matthew-t-smith/visual-programming#60]
I would suggest a few more changes to make the `GraphView` a little more user-friendly.

1) Increase the size of the modal pop-up. It will never be large enough to handled the biggest data sets. Right now it has a `max-width` of 500px (at smaller breakpoints it increases to the window size).
2) Before data is loaded, the button options are currently 'Accept' and 'Load'. I would propose changing 'Accept' to 'Cancel'.
3) After data is loaded and viewing it graphically, the button text is 'Accept'. I would propose changing this to 'Done' or 'Okay'.
4) Cell highlighting alternates by row and column (e.g. A1 is shaded, B1 is not and the opposite for the second row). I would propose cell shading is constant by row (e.g. row 1 is shaded, row 2 is not), without alternating by column.

<img width="525" alt="Screen Shot 2020-04-18 at 9 29 36 AM" src="https://user-images.githubusercontent.com/35537944/79639058-215b7080-8157-11ea-86c2-5e4563ea7e47.png">

**Comment by diegostruk1** [comment]
Another suggestion: clicking on graph view button in a node that does not have data loaded should give a popup saying that there is no data to view (or have the graph button disabled).
![2020-04-18 11 40 14](https://user-images.githubusercontent.com/7118562/79642155-e6af0380-8169-11ea-9f2a-2fccf01c389c.gif)
